window.PIXEL_APPS = [
  {
    id: "twitter-translator",
    name: "TwitterWithBaiduTranslator",
    note: "Chrome Extension for X/Twitter Translation",
    href: "https://chromewebstore.google.com/detail/xwitter-translator-bear-x/jfoppggphfkahfohdamcijagmpgffenp",
    intro: "One-click translation inside the X/Twitter timeline, powered by Google, Baidu, and multiple LLM engines.",
    iconSrc: "./assets/icons/languages-sharp.svg",
    fallback: "TW",
    badge: "question",
  },
  {
    id: "breathe-ball",
    name: "BreatheBall",
    note: "Guided Breathing for Focus and Calm",
    href: "https://breatheball.xiaoxiong.app/",
    intro: "A minimalist breathing trainer that helps you relax, focus, and quickly settle into a steady rhythm.",
    iconSrc: "./assets/icons/waves.svg",
    fallback: "BR",
    badge: "mushroom",
  },
  {
    id: "xgp-box",
    name: "XGPBox",
    note: "Xbox Game Pass Tracker and Explorer",
    href: "https://gpbox.xiaoxiong.app/",
    intro: "Track new arrivals, leaving titles, and popular picks on Xbox Game Pass to find great games faster.",
    iconSrc: "./assets/icons/gamepad-sharp.svg",
    fallback: "XB",
    badge: "coin",
  },
  {
    id: "daily",
    name: "Daily",
    note: "Personal Blog and Journal",
    href: "https://daily.xiaoxiong.app/",
    intro: "A personal blog and journal with tech notes, life reflections, and long-term project writeups.",
    iconSrc: "./assets/icons/calendar-text-sharp.svg",
    fallback: "DY",
    badge: "question",
  },
  {
    id: "podcast",
    name: "Podcast",
    note: "An English Learning Podcast",
    href: "https://enpod.podcast.xyz/",
    intro: "An AI-assisted English learning podcast that breaks episodes into digestible segments for comprehension-first listening.",
    iconSrc: "./assets/icons/rss-square-sharp.svg",
    fallback: "PC",
    badge: "coin",
  },
];
