window.PIXEL_HOME = {
  header: {
    title: "Xiaoxiong Apps",
    subtitle: "Small apps, tools and experiments by Xiaoxiong.",
  },
  featured: ["xgp-box", "breathe-ball"],
  sections: [
    {
      id: "tools",
      title: "Tools",
      tone: "tools",
      items: [
        "xgp-box",
        "breathe-ball",
        "twotwo-girl",
        "twitter-translator",
        "anki-learning-by-list",
      ],
    },
    {
      id: "content",
      title: "Content",
      tone: "content",
      items: ["daily", "podcast"],
    },
  ],
  apps: [
    {
      id: "twitter-translator",
      name: "Twitter UI Translator",
      shortDesc: "Chrome extension for X/Twitter translation.",
      longDesc:
        "Translate X/Twitter posts in one click with Google, Baidu, or your own LLM API provider.",
      tags: ["Tool", "Browser Extension"],
      href: "https://chromewebstore.google.com/detail/xwitter-translator-bear-x/jfoppggphfkahfohdamcijagmpgffenp",
      iconSrc: "./assets/icons/xwitter-translator-bear.png",
      fallback: "TW",
      theme: "sunset",
    },
    {
      id: "twotwo-girl",
      name: "22 Girl",
      shortDesc: "Pixel Bilibili danmaku platformer.",
      longDesc:
        "Turn live Bilibili danmaku into moving platforms and guide 22 Niang through a lightweight pixel platformer while you watch.",
      tags: ["Tool", "Game"],
      href: "https://chromewebstore.google.com/detail/22%E5%A8%98%E5%BC%B9%E5%B9%95%E5%A4%A7%E5%86%92%E9%99%A9/ffipgjffmghinekaaolhingoncpnenol",
      iconSrc: "./assets/icons/twotwo-girl.png",
      iconFit: "cover",
      fallback: "22",
      theme: "leaf",
    },
    {
      id: "breathe-ball",
      name: "Breathe Ball",
      shortDesc: "Guided breathing for focus and calm.",
      longDesc:
        "A lightweight breathing app with a floating orb, flexible rhythm presets, and quick calm resets.",
      tags: ["Tool", "Wellness"],
      href: "https://breatheball.xiaoxiong.app/",
      iconSrc: "./assets/icons/breatheball.png",
      iconFit: "cover",
      fallback: "BR",
      theme: "sky",
      featuredLabel: "Featured Tool",
    },
    {
      id: "xgp-box",
      name: "Game Pass Box",
      shortDesc: "Xbox Game Pass tracker and explorer.",
      longDesc:
        "Discover what is actually worth playing next on Game Pass, ranked by player stats, value, and release signals.",
      tags: ["Tool", "Game"],
      href: "https://gpbox.xiaoxiong.app/",
      iconSrc: "./assets/icons/game-pass-box.png",
      fallback: "XB",
      theme: "gold",
      featuredLabel: "Featured Tool",
    },
    {
      id: "daily",
      name: "Daily",
      shortDesc: "Personal blog and journal.",
      longDesc:
        "Essays, reading notes, tech posts, and everyday reflections collected in one long-running personal blog.",
      tags: ["Content", "Writing"],
      href: "https://daily.xiaoxiong.app/",
      iconSrc: "./assets/icons/daily-favicon.ico",
      fallback: "DY",
      theme: "coral",
    },
    {
      id: "podcast",
      name: "Podcast",
      shortDesc: "An English learning podcast.",
      longDesc:
        "An AI-assisted English learning podcast that breaks strong episodes into five-minute chunks with Chinese summaries.",
      tags: ["Content", "Audio"],
      href: "https://enpod.podcast.xyz/",
      iconSrc: "./assets/icons/podcast-english.jpg",
      iconFit: "cover",
      fallback: "PC",
      theme: "mint",
    },
    {
      id: "anki-learning-by-list",
      name: "Learning by List",
      shortDesc: "Anki add-on for note-based review.",
      longDesc:
        "Browse the current Anki deck as a note-based list with configurable columns, inline audio playback, and faster scanning.",
      tags: ["Tool", "Study"],
      href: "https://ankiweb.net/shared/info/884041405",
      iconSrc: "./assets/icons/book-list.svg",
      fallback: "AL",
      theme: "violet",
    },
  ],
};
